### PR TITLE
feature/UCAF-645-new-contract-messages

### LINKED ISSUE #645: UCAF - new contract messages
**Aus welchem Grund ist die Idee oder Erweiterung hilfreich?**
Sieht besser aus 

**Was soll passieren, wie soll die Idee oder Erweiterung umgesetzt werden?**
- [ ] In Contract Eventhandler einbauen
- [ ] evtl. pattern registrieren

**Sonstiges**
Füge hier jeglichen anderen Kontext oder Screenshots zur Funktionsanfrage hinzu.

### PR DESCRIPTION
**Pull request by Gelegenheitscode**
closes #645

### CODE REVIEW

**Comment by Gelegenheitscode** [comment]
@rettichlp schon 9 tage...

**Comment by rettichlp** [comment]
blocked until #479 is merged

**Review by rettichlp — APPROVED** [review]
Review ok

**Comment by rettichlp** [comment]
because of a youth-friendly update of the server, there needs to be an update for weapons and other names, so this pr is no longer blocked and can be merged too

**Pull request merged**
